import Head from 'next/head'
import { useState, useEffect } from 'react'
import Link from 'next/link'
import Image from 'next/image'
import img1 from '../../public/assets/logos/logo-accueil.png'
import flagFr from '../../public/assets/icones/flag-fr.gif'
import flagEng from '../../public/assets/icones/flag-eng.gif'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import { useTranslation } from 'react-i18next';


const inter = Inter({ subsets: ['latin'] })


export default function Home(props) {

// Translation library
  const { t, i18n } = useTranslation();
  const setLocaleEn = () => {
    i18n.changeLanguage('en')
  }
  const setLocaleFr = () => {
    i18n.changeLanguage('fr')
  }


  // Diaporama Background 
  const backgroundImages = [
    'assets/img/backgroundHome/img0.jpeg',
    'assets/img/backgroundHome/img1.jpeg',
    'assets/img/backgroundHome/img2.jpeg',
    'assets/img/backgroundHome/img3.jpeg',
    // Ajoutez d'autres URL d'images ici
  ];

  const [currentImageIndex, setCurrentImageIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImageIndex((prevIndex) => (prevIndex + 1) % backgroundImages.length);
    }, 4000);
    return () => clearInterval(interval);
  }, []);

  const backgroundImageStyle = {
    backgroundImage: `url(${backgroundImages[currentImageIndex]})`,
  };




  return (
    <>
      <Head>
        <title>Coté Design Beta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.logoContainer}>
          <div className={styles.logo}>
            <div className="logo"><Image className={styles.logoImg} src={img1} alt='Logo côté design' priority/></div>
            <div className={styles.textLogo}>ARCHITECTURE & MISE EN OEUVRE</div>
            <div className={styles.textAdress}>
              <p>4 rue Gambetta 06560 Valbonne</p>
            </div>

            <div className={styles.flagContainer}>
              <div className="flag-french">
                <Link href={'accueil'} onClick={setLocaleFr}>
                  <Image src={flagFr} width="50" height="35" alt='French flag' />
                  <br></br><span> Français</span>
                </Link>
              </div>
              <div className="flag-english">
                <Link className='navbar-brand mx-4' href={'/accueil'} onClick={setLocaleEn}>
                  <Image src={flagEng} width="50" height="35" alt='English flag'/>
                  <br></br><span> English</span>
                </Link>
              </div>
            </div>
          </div>
        </div>
        <h1>Bienvenue sur coté Design</h1>

        {/* Background diaporama  */}
        <section className={styles.backgroundSection}>
          
          <div className={`${styles.backgroundImage} ${styles.animate}`}  style={backgroundImageStyle}></div>
        <div className={styles.scanlines}></div>
        </section>
        {/* Scanlines  */}
      </main>
    </>
  )
}
